### ISSUE TITLE
hifigan checkpoint file

### ISSUE THREAD

**Issue by carrrlosss** [shivammehta25/OverFlow#20]
hello @shivammehta25 

looks like the hifigan checkpoint download links are gone or have changed, do you have a .ckpt file for hifigan by any chance?

**Comment by shivammehta25** [comment]
You can find some checkpoints here https://drive.google.com/drive/folders/1-eEYTB5Av9jNql0WGBlRoi-WH2J7bp5Y. Link from their official repository https://github.com/jik876/hifi-gan
